import "server-only"
import type { Attachment } from "resend"
import {
  BRAND_BACKGROUND,
  BRAND_MUTED,
  BRAND_PRIMARY,
  BRAND_SECONDARY,
  EMAIL_HEADER_BACKGROUND,
  absoluteUrl,
} from "@/lib/email/brand"
import { getResendClient, getResendFromAddress, logResendSendError } from "@/lib/email/resendClient"
import { getTwookyLogoInlineAttachment, twookyLogoEmailImgTag } from "@/lib/email/twookyLogoInline"

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

type TeamCredentialsEmailInput = {
  email: string
  password: string
  roleLabel: string
  generatedByName: string
  isReset: boolean
}

function buildTeamCredentialsEmail(input: TeamCredentialsEmailInput) {
  const subject = input.isReset
    ? "Your Twooky admin password was reset"
    : "Your Twooky admin team account is ready"
  const loginUrl = absoluteUrl("/login")
  const logoImg = twookyLogoEmailImgTag()
  const safeEmail = escapeHtml(input.email)
  const safePassword = escapeHtml(input.password)
  const safeRole = escapeHtml(input.roleLabel)
  const safeGeneratedByName = escapeHtml(input.generatedByName)
  const safeLoginUrl = escapeHtml(loginUrl)

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:${BRAND_BACKGROUND};font-family:Inter,Segoe UI,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:${BRAND_BACKGROUND};padding:32px 16px;">
    <tr>
      <td align="center">
        <table role="presentation" width="100%" style="max-width:560px;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e2e8f0;">
          <tr>
            <td bgcolor="#ffffff" style="padding:28px 28px 12px 28px;background-color:${EMAIL_HEADER_BACKGROUND};border-bottom:1px solid #e2e8f0;">
              ${logoImg}
            </td>
          </tr>
          <tr>
            <td style="padding:28px;">
              <p style="margin:0 0 8px 0;font-size:13px;font-weight:600;letter-spacing:0.06em;text-transform:uppercase;color:${BRAND_SECONDARY};">Admin team access</p>
              <h1 style="margin:0 0 12px 0;font-size:22px;line-height:1.25;color:${BRAND_PRIMARY};font-weight:700;">
                ${input.isReset ? "Your password was regenerated" : "Your team account is ready"}
              </h1>
              <p style="margin:0 0 20px 0;font-size:16px;line-height:1.55;color:#334155;">
                ${input.isReset ? "A top admin regenerated your password." : "A top admin created your team account."} Use the credentials below to sign in.
              </p>
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #e2e8f0;border-radius:10px;">
                <tr><td style="padding:14px 16px;font-size:14px;color:#334155;"><strong>Email:</strong> ${safeEmail}</td></tr>
                <tr><td style="padding:0 16px 14px 16px;font-size:14px;color:#334155;"><strong>Password:</strong> ${safePassword}</td></tr>
                <tr><td style="padding:0 16px 14px 16px;font-size:14px;color:#334155;"><strong>Role:</strong> ${safeRole}</td></tr>
              </table>
              <p style="margin:18px 0 0 0;font-size:14px;line-height:1.5;color:${BRAND_MUTED};">
                Generated by: ${safeGeneratedByName}
              </p>
              <p style="margin:18px 0 0 0;">
                <a href="${safeLoginUrl}" style="display:inline-block;padding:12px 24px;background:${BRAND_PRIMARY};color:#ffffff;text-decoration:none;border-radius:8px;font-weight:600;font-size:15px;">Sign in to Twooky</a>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`

  const text = [
    input.isReset ? "Your Twooky admin password was reset" : "Your Twooky admin team account is ready",
    "",
    `Email: ${input.email}`,
    `Password: ${input.password}`,
    `Role: ${input.roleLabel}`,
    `Generated by: ${input.generatedByName}`,
    "",
    `Login: ${loginUrl}`,
  ].join("\n")

  const attachments: Attachment[] = []
  const logoAtt = getTwookyLogoInlineAttachment()
  if (logoAtt) attachments.push(logoAtt)

  return { subject, html, text, attachments }
}

export async function sendAdminTeamCredentialsEmail(input: TeamCredentialsEmailInput): Promise<boolean> {
  const resend = getResendClient()
  if (!resend) return false

  const { subject, html, text, attachments } = buildTeamCredentialsEmail(input)
  const sent = await resend.emails.send({
    from: getResendFromAddress(),
    to: [input.email.trim()],
    subject,
    html,
    text,
    ...(attachments.length > 0 ? { attachments } : {}),
  })

  if (sent.error) {
    logResendSendError("admin team credentials", sent.error)
    return false
  }
  return true
}
